CREATE DATABASE AHCP_DATA;
USE AHCP_DATA;
CREATE TABLE NEW_PATIENT(PATIENT_NUMBER VARCHAR(20) PRIMARY KEY,NAME_OF_PATIENT VARCHAR(100) NOT NULL,
ADDRESS_lOCALITY VARCHAR(100) NULL,AGE INT NULL,SEX CHAR(1) NOT NULL CHECK(SEX IN ('M','F')),
NHIS_NUMBER VARCHAR(20) UNIQUE,VISIT_DATE DATE NOT NULL,UNIQUE(NHIS_NUMBER,VISIT_DATE));

CREATE TABLE OLD_PATIENT(PATIENT_NUMBER VARCHAR(20) PRIMARY KEY,NAME_OF_PATIENT VARCHAR(100) NOT NULL,
ADDRESS_lOCALITY VARCHAR(100) NULL,AGE INT NULL,SEX CHAR(1) NOT NULL CHECK(SEX IN ('M','F')),
NHIS_NUMBER VARCHAR(20) UNIQUE NULL,VISIT_DATE DATE NOT NULL,UNIQUE(NHIS_NUMBER,VISIT_DATE));

CREATE TABLE ANTENATAL_CARE(VISIT_DATE DATE NOT NULL,PATIENT_NUMBER VARCHAR(20) PRIMARY KEY,
NAME_OF_PATIENT VARCHAR(100) NOT NULL,ADDRESS_LOCALITY VARCHAR(100) NULL,AGE INT NULL,NHIS_NUMBER VARCHAR(20) UNIQUE,
UNIQUE(NHIS_NUMBER,VISIT_DATE));

ALTER TABLE NEW_PATIENT MODIFY COLUMN  PATIENT_NUMBER VARCHAR(20) AFTER VISIT_DATE;
ALTER TABLE OLD_PATIENT MODIFY COLUMN PATIENT_NUMBER VARCHAR(20) AFTER VISIT_DATE;
SELECT * FROM NEW_PATIENT;
SELECT * FROM OLD_PATIENT;
#KEYYING ANTENATAL_CARE
SELECT * FROM ANTENATAL_CARE;
INSERT INTO ANTENATAL_CARE(VISIT_DATE,PATIENT_NUMBER,NAME_OF_PATIENT,ADDRESS_LOCALITY,AGE,NHIS_NUMBER)VALUES
(CURRENT_DATE - INTERVAL 1 DAY,"001178/26","RAMATU ADAMS","ABOASO","26","99108");
ALTER TABLE ANTENATAL_CARE ADD CONSTRAINT UNIQUE (PATIENT_NUMBER);
ALTER TABLE ANTENATAL_CARE MODIFY PATIENT_NUMBER VARCHAR(20) NULL;
ALTER TABLE ANTENATAL_CARE ADD CONSTRAINT UNIQUE(NHIS_NUMBER);
DESCRIBE ANTENATAL_CARE;
ALTER TABLE ANTENATAL_CARE DROP PRIMARY KEY;
ALTER TABLE ANTENATAL_CARE MODIFY PATIENT_NUMBER VARCHAR(20) NULL;
ALTER TABLE ANTENATAL_CARE ADD CONSTRAINT UNIQUE(PATIENT_NUMBER);
SELECT * FROM ANTENATAL_CARE WHERE NHIS_NUMBER = "98496";
#COUNTING THE NUMBER OF ROWS
SELECT COUNT(*) FROM ANTENATAL_CARE;
#DROPPING UNIQUE KEY
ALTER TABLE ANTENATAL_CARE DROP INDEX PATIENT_NUMBER_2;
SHOW INDEX FROM ANTENATAL_CARE;
ALTER TABLE ANTENATAL_CARE DROP CONSTRAINT NHIS_NUMBER_2;
ALTER TABLE ANTENATAL_CARE DROP CONSTRAINT PATIENT_NUMBER;
SELECT COUNT(*) FROM ANTENATAL_CARE WHERE ADDRESS_LOCALITY = "ABOASO" AND AGE < 25;

SELECT COUNT(*) AS TOTAL_COUNT_20_27 FROM ANTENATAL_CARE WHERE AGE BETWEEN 12 AND 22;



#NEW PATIENT KEYYING
RENAME TABLE NEW_PATIENT TO NEW_PATIENT_INSURED;
ALTER TABLE NEW_PATIENT DROP PRIMARY KEY;
DESCRIBE NEW_PATIENT_INSURED;
ALTER TABLE NEW_PATIENT ADD CONSTRAINT UNIQUE(PATIENT_NUMBER);
ALTER TABLE NEW_PATIENT MODIFY PATIENT_NUMBER VARCHAR(20) NULL;
ALTER TABLE NEW_PATIENT_INSURED MODIFY NHIS_NUMBER VARCHAR(20) NULL;
INSERT INTO NEW_PATIENT_INSURED(VISIT_DATE,PATIENT_NUMBER,NAME_OF_PATIENT,ADDRESS_LOCALITY,AGE,SEX,NHIS_NUMBER)VALUES
(CURRENT_DATE - INTERVAL 1 DAY,"003064/26","ABDUL BASIT HUMULHAIR","ABOASO","4","F","24078");
UPDATE NEW_PATIENT_INSURED SET PATIENT_NUMBER = "002944/26" WHERE NAME_OF_PATIENT  = "ANANE SARAH";
ALTER TABLE NEW_PATIENT_INSURED MODIFY AGE VARCHAR(20);
SELECT * FROM NEW_PATIENT_INSURED WHERE PATIENT_NUMBER = "003033/26";
SELECT * FROM NEW_PATIENT_INSURED;

#CREATING TABLE FOR NEW NON-INSURED
CREATE TABLE NEW_PATIENT_NON_INSURED(VISIT_DATE DATE,PATIENT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
NAME_OF_PATIENT VARCHAR(20) NULL,ADDRESS_LOCALITY VARCHAR(20) NULL,AGE VARCHAR(30) NULL,
SEX CHAR(1) NOT NULL CHECK(SEX IN ('M','F')),NHIS_NUMBER VARCHAR(20) NULL);
ALTER TABLE NEW_PATIENT_NON_INSURED MODIFY SEX VARCHAR(20);
DESCRIBE NEW_PATIENT_NON_INSURED;
INSERT INTO NEW_PATIENT_NON_INSURED(VISIT_DATE,PATIENT_NUMBER,NAME_OF_PATIENT,ADDRESS_LOCALITY,AGE,SEX)
VALUES(CURRENT_DATE - INTERVAL 1 DAY,"1017/26","KAMIL ABDUL MUMIN","ABOASO","23","M");
SELECT * FROM NEW_PATIENT_NON_INSURED;
UPDATE NEW_PATIENT_NON_INSURED SET VISIT_DATE = CURRENT_DATE - INTERVAL 1 DAY WHERE PATIENT_NUMBER = "988/26";

#OLD_PATIENT KEYYING
DESCRIBE OLD_PATIENT;
SELECT * FROM OLD_PATIENT;
UPDATE OLD_PATIENT SET ADDRESS_lOCALITY = "ABOASO" WHERE NAME_OF_PATIENT = "NANA GYAMAN PEMSAN II";
#MAKING VISIT_DATE FIRST
ALTER TABLE OLD_PATIENT MODIFY  VISIT_DATE DATE FIRST;
ALTER TABLE OLD_PATIENT MODIFY NAME_OF_PATIENT VARCHAR(100) AFTER PATIENT_NUMBER;
ALTER TABLE OLD_PATIENT DROP PRIMARY KEY;
ALTER TABLE OLD_PATIENT MODIFY PATIENT_NUMBER VARCHAR(20) NULL;
ALTER TABLE OLD_PATIENT MODIFY COLUMN AGE VARCHAR(50);
INSERT INTO OLD_PATIENT(VISIT_DATE,PATIENT_NUMBER,NAME_OF_PATIENT,ADDRESS_LOCALITY,AGE,SEX,NHIS_NUMBER)VALUES(
CURRENT_DATE - INTERVAL 9 DAY,"00114/26","APPIAH STEPHEN","WADIE","46","M","88960");
SELECT COUNT(*) FROM OLD_PATIENT;




